### ISSUE TITLE
Chunk throwing breaks drop-in replacement

### ISSUE THREAD

**Issue by mdwyer6** [toss/es-toolkit#126]
The chunk method throws for int sizes less than 1 (which you've documented). This is different from lodash behavior which always returns an empty array and therefore breaks with the stated design goal of being a drop-in replacement.

**Comment by raon0211** [comment]
You're right.

In my opinion, throwing an exception would be a better design choice, but it seems that we should respect lodash's behavior when we aim to be a drop-in replacement.

We might create a new subpath export, namely `es-toolkit/compat`, which is 100% compatible with lodash (verified by lodash’s test code), while defining new defaults that are more desirable for modern JavaScript environments.

**Comment by raon0211** [comment]
Hello, this was fixed in [this commit](https://github.com/toss/es-toolkit/commit/acb74650a67a0ba67b1d9a0ce1dbbf3aa0c8ae49#diff-3c1eb8b46882f5cb53b8cdd0153f2a5581d4e46ba1c820d0dafbd6584c9a1c5cR27).

You can import `chunk` from `es-toolkit/compat` in the next release, which provides 100% feature parity with lodash.
