### ISSUE TITLE
In what way does es-toolkit provide extra support for tree-shaking?

### ISSUE THREAD

**Issue by rauschma** [toss/es-toolkit#132]
* I’m genuinely curious: How does es-toolkit’s support for tree-shaking go beyond using ESM?
  * [One version of Lodash](https://www.npmjs.com/package/lodash-es) puts each function into a separate module: I understand why they do that but I wish there were a better way.
* I haven’t seen that explained anywhere – hence my question.

**Comment by raon0211** [comment]
What you've mentioned covers most of what's needed for proper tree-shaking:

1. Put each function into a separate module.
2. Add `sideEffects: false` in package.json.

This is because `sideEffects: false` means that bundlers should only keep files that have functions or variables imported in the service code, while all other files should be completely removed from the bundle. Therefore, if we split each of our functions, we achieve complete tree-shaking support.

In contrast, if all functions and variables are in a single file, adding `sideEffects: false` wouldn't be effective. This is because having even one function or variable imported prevents the entire file from being dropped. (In this case, the file can only be minified with minifiers)

---

The significant difference in bundle size between lodash and es-toolkit comes from their implementations. es-toolkit utilizes modern JavaScript APIs and TypeScript types, resulting in a very simple implementation. On the other hand, lodash relies on legacy APIs and includes defensive checks for argument types at runtime, which increases its bundle size significantly.

**Comment by rauschma** [comment]
Thanks for your detailed answer! (If you wanted to, you could use your reply as an FAQ entry in the es-toolkit Guide.)
