### ISSUE TITLE
Support `cancel` to `throttle`

### ISSUE THREAD

**Issue by Hanna922** [toss/es-toolkit#59]
The existing [throttle](https://es-toolkit.slash.page/reference/function/throttle.html#throttle) function does not include a cancel feature.
How about adding a cancel feature to the `throttle` function?

Additionally, using AbortSignal can also be useful.

Let me know your opinion. Thank you

**Comment by raon0211** [comment]
Hi, thanks for your suggestion! 

I’ve thought about adding a `cancel` feature to `throttle`, but the way `throttle` works makes it tricky. Since `throttle` doesn't actually queue any asynchronous tasks, it’s hard to define what exactly would be canceled. That’s why we haven’t included a `cancel` option in `throttle`.

What are your thoughts?

**Comment by Hanna922** [comment]
I simply thought that the `cancel` feature would cancel the pending function and make it immediately callable by setting lastCallTime to null. For example, it should be able to pass the following test code.

```ts
it('should call the function immediately after cancel is called', async () => {
  const func = vi.fn();
  const throttledFunc = throttle(func, 100);

  throttledFunc();
  expect(func).toHaveBeenCalledTimes(1);

  throttledFunc.cancel();
  throttledFunc();
  expect(func).toHaveBeenCalledTimes(2);
});
```

How do you feel about providing this kind of `cancel`?

**Comment by raon0211** [comment]
As you mentioned, providing those kinds of `cancel` options might be helpful.

However, I'm not sure if it is really that beneficial. For `debounce`, we have to cancel the debounced function when the component is cleaned up, but for `throttle`, there's no need to do so. 

Additionally, since we can only abort `AbortController`s once, it might not align well with the definition of `cancel` for `throttle`.

So, because it is not a major use case, I think we might not support `cancel` for `throttle` in `es-toolkit`. What do you think?

**Comment by Hanna922** [comment]
Yes, I agree that it is not a major use case. I'll close this issue. Thank you 🙇🏻‍♀️
