### ISSUE TITLE
pick's type definition should support keys that don't exist in the object being picked from

### ISSUE THREAD

**Issue by ben519** [toss/es-toolkit#838]
Consider this example:

```ts
interface Person {
  id: string;
  age: number;
}

const person: Person = { id: "123", age: 30 };
const picked = pick(person, ["id", "name"] as const);
```

This generates the error

> Type '"name"' is not assignable to type 'keyof Person'.

<img width="807" alt="Screenshot 2024-11-22 at 10 09 29 AM" src="https://github.com/user-attachments/assets/753c3412-59fb-48bb-89bb-f9ad3bdf638c">

My understanding is that this should be possible; `pick()` should simply ignore/exclude keys that don't exist in the object. At least, that's the way I've always used it with vanilla JavaScript.

**Comment by raon0211** [comment]
Hi there! 😊

I understand that the behavior differs from vanilla JavaScript. However, this is intentional in our library. In `es-toolkit`, our design principle is to provide strict types wherever possible. 

If you want to pick properties as shown in the example code, you can cast the property key array to either `any[]` or `Array<keyof Person>`.

Let me know if you need further clarification!
